import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Stitch design system
        'secondary-fixed':           '#efe0ce',
        'surface-container-high':    '#e1e8fd',
        'surface-container-low':     '#f1f3ff',
        'inverse-surface':           '#293040',
        'secondary-fixed-dim':       '#d2c5b3',
        'surface-container-lowest':  '#ffffff',
        'primary-fixed-dim':         '#94d1d1',
        'champagne-glint':           '#F2E8DC',
        'on-tertiary-fixed-variant': '#5a4229',
        'surface-variant':           '#dce2f7',
        'on-primary':                '#ffffff',
        'on-secondary-container':    '#6b6153',
        'aviation-navy':             '#1A242F',
        'surface-container-highest': '#dce2f7',
        'primary-fixed':             '#b0eeed',
        'sand-dark':                 '#A68D74',
        'on-surface-variant':        '#3f4848',
        'on-error-container':        '#93000a',
        'tertiary-container':        '#574027',
        'tertiary':                  '#3f2a13',
        'surface-bright':            '#f9f9ff',
        'on-primary-fixed':          '#002020',
        'tertiary-fixed-dim':        '#e3c19f',
        'outline-variant':           '#bfc8c8',
        'on-tertiary-fixed':         '#291803',
        'primary':                   '#003434',
        'on-secondary-fixed':        '#211b0f',
        'secondary-container':       '#ecdecb',
        'surface-tint':              '#296767',
        'on-primary-fixed-variant':  '#044f4f',
        'on-tertiary':               '#ffffff',
        'bone-white':                '#F9F8F6',
        'inverse-primary':           '#94d1d1',
        'error-container':           '#ffdad6',
        'tertiary-fixed':            '#ffddbb',
        'inverse-on-surface':        '#edf0ff',
        'surface-dim':               '#d3daef',
        'on-tertiary-container':     '#cdac8c',
        'outline':                   '#6f7978',
        'on-surface':                '#141b2b',
        'on-secondary':              '#ffffff',
        'primary-container':         '#004d4d',
        'on-background':             '#141b2b',
        'surface-container':         '#e9edff',
        'on-secondary-fixed-variant':'#4e4538',
        'on-primary-container':      '#80bdbc',
        'secondary':                 '#675d4f',
        // Legacy — used by non-homepage components
        brand: {
          50: '#f0f4ff', 100: '#e0e9ff', 200: '#c0d2ff', 300: '#93b2ff',
          400: '#6088ff', 500: '#3a5fff', 600: '#1e3ff5', 700: '#1630e0',
          800: '#1828b5', 900: '#1a278e', 950: '#111660',
        },
        gold: { 400: '#f5c842', 500: '#e8b400', 600: '#c49700' },
      },
      fontFamily: {
        sans:              ['Inter', 'system-ui', 'sans-serif'],
        'headline-md':     ['"Playfair Display"', 'serif'],
        'headline-lg':     ['"Playfair Display"', 'serif'],
        'display-lg':      ['"Playfair Display"', 'serif'],
        'display-lg-mobile': ['"Playfair Display"', 'serif'],
        'label-caps':      ['Inter', 'sans-serif'],
        'label-sm':        ['Inter', 'sans-serif'],
        'body-md':         ['Inter', 'sans-serif'],
        'body-lg':         ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-md':       ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg':       ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'display-lg':        ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-caps':        ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
        'label-sm':          ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'body-md':           ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg':           ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
      spacing: {
        'gutter':         '24px',
        'section-gap':    '80px',
        'margin-desktop': '64px',
        'margin-mobile':  '20px',
        'container-max':  '1280px',
        'unit':           '8px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}

export default config
